# Generated by Django 5.0.6 on 2025-01-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=250)),
                ('company_location', models.CharField(blank=True, max_length=150, null=True)),
                ('starting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('ending_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career_Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificcate_name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_description', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('starting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('ending_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database_Consaltent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database_Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('hours', models.CharField(blank=True, max_length=20, null=True)),
                ('participants', models.CharField(blank=True, max_length=20, null=True)),
                ('company_location', models.CharField(max_length=150)),
                ('starting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('ending_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('batch', models.ImageField(blank=True, null=True, upload_to='')),
                ('experience_percentage', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('linkedIn_link', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=150)),
                ('starting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('ending_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('presented_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('short_description', models.CharField(blank=True, max_length=250, null=True)),
                ('broad_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='app.tutorialname')),
            ],
        ),
    ]
