# Generated by Django 5.0.6 on 2025-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tutorial_broad_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='topic',
            field=models.CharField(max_length=80),
        ),
    ]
